//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AspNet.CRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jumpers
    {
        public int IDJumpers { get; set; }
        public int QntdJumpers { get; set; }
        public string TypeJumpers { get; set; }
    }
}
